name: Development Container
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'production'

jobs:
  Login_to_Server:
    runs-on: ubuntu-latest
    steps:
      - name: Connect via SSH using password AND Run Script
        run: |
          # Ensure the host key is added to prevent SSH prompt
          sshpass -p ${{ secrets.SSH_PASSWORD }} ssh -o StrictHostKeyChecking=no root@192.64.87.254 "echo $(date) >> fromGitHubActions.txt && ./frontend_git_pm2.sh"

        # - name: Set up SSH key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      #     chmod 600 ~/.ssh/id_rsa
      #     ssh-keyscan -H 192.64.87.254 >> ~/.ssh/known_hosts
      #   env:
      #     SSH_PRIVATE_KEY: ${{ vars.SSH_PRIVATE_KEY }}

      # - name: Download_artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: file_dare

      # - name: Transfer files via SCP
      #   run: |
      #       rsync -avz . 192.64.87.254:/root/api_backend
  # Uncomment and configure second-job if necessary
  # second-job:
  #   needs: Prequisite
  #   timeout-minutes: 3
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: file_dare
  #     - name: List all files
  #       run: ls -ltra
  #     - name: Tests
  #       uses: cloudposse/github-action-docker-compose-test-run@main
  #       with:
  #         file: docker-compose.yaml
  #         service: votar-app
  #     - name: Checking Docker container
  #       run: |
  #         docker-compose exec votar-app /bin/bash
  #         echo $MONGO_URI
  #         docker-compose ps
  #         docker network inspect votar_backend_api_default
  #         docker network inspect votar_backend_api_mongodb_1
  #         ping mongodb
  #         nc -zv mongodb 27017
  #         docker-compose logs votar-app
