name: Push to Another Repo

on:
  push:
    branches:
      - main

jobs:
  push-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "Votar-production"
          git config --global user.email "votarhq1@gmail.com"

      - name: Push Code to Target Repository
        run: |
          git remote add target https://Tony-kNz:${{ secrets.PAT_TOKEN }}@github.com/Tony-kNz/https://github.com/VotarDev/votar-frontend-v2.git
          git push -u target main
